include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true # show warning if 'print' is used
    prefer_const_constructors: true # enforce const where possible
    unnecessary_this: false # disable 'avoid unnecessary this'
    prefer_const_declarations: true
    sized_box_for_whitespace: true
    library_names: true
