include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    unnecessary_this: false
    prefer_const_declarations: true
    sized_box_for_whitespace: true
    library_names: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_parameters: true
    prefer_final_in_for_each: true
    avoid_function_literals_in_foreach_calls: true
